###########################################################################################################
##                                                                                                       ##
## Title: Medusa cell speed and movement characteristics after inhibition of different components of the ##
##        cytoskeleton                                                                                   ##
## Author: Fernando J. Bascon                                                                            ##
## Affiliations: Multicellgenome Lab, Institut de Biologia Evolutiva, CSIC-UPF                           ##
## Date: 2023-2026                                                                                       ##
##                                                                                                       ##
###########################################################################################################

## For this experiment, Medusa cells were treated with different inhibitors for different components of the
## cytoskeleton: 
## - Control: untreated Medusa cells (9 Medusa cells)
## - DMSO Control: Medusa cells treated in DMSO since the inhibitors are diluted in it (35 Medusa cells)
## - CK666: Actin polymerization inhibitor (41 Medusa cells)
## - Latrunculin: Actin depolymerator (27 Medusa cells)
## - Blebbistatin: Myosin inhibitor (33 Medusa cells)

## The Medusa cells were filmed after the addition of each inhibitor. The videos were analysed using Fiji (1),
## this time, using TrackMate plugin (2,3). The control untreated Medusa cells used were the same ones as for the
## analysis before and after Head/Tail separation, that were re-analysed using TrackMate (2,3) for this experiment
## (more information about it down below). 

## The R plugins used in this analysis were: 
## - ggplot2 (4)
## - ggsignif (5)

library(ggplot2)
library(ggsignif)

###########################################################################################################
## 1. Data preparation                                                                                   ##
###########################################################################################################

## The track data generated by TrackMate (2,3) has info about all cells present in the video, not only of Medusa
## cells, for this reason, before doing any analysis we selected the Medusaa cell tracks from each file, 
## extracted the mean speed of each of them and group them in one variable that will be used later for the 
## statistical analysis and plotting. 

## Each sample was composed by different videos, meaning, each sample has a set of various .csv files. All
## these .csv data files are located in the folder TrackData and classified by sample. For the controls, 
## only a subset of the Medusa cells used in the analysis were we characterized the movement before and
## after Head/Tail separation was used. The reason for this subset (Medusa cells 1 through 7, 9 and 14) was 
## TrackMate (2,3). The way this plugin works need the cells to not be grouped in big clumps nor too crowded.
## For this reason, we could not use this approach for all the Medusa cells analysed before, even though we
## could do it manually at the time. 

## Also, the different inhibitors were added while the video was been taken. This induced some media flow that 
## pushed all the cells present. To try to remove this artifact, we decided to track some controls 
## (coenocytes/uninuclear cells) from inside each video and normalize the speed data by dividing the Medusa 
## cells speed by the mean of all the control speeds.

##############
##  Control ##
##############

## Differently from the rest of the data files, untreated controls only have the Medusa cells/Coenocyte/Uninuclear cell
## data in the .csv files, so we do not need to manually extract the tracks corresponding to them. The Medusa cells 
## analysed where the same ones from the Before and After Head/Tail separation analysis. Not all of them were used, 
## only MC1-7, MC9 and MC14 where used. 

ControlMCData <- read.table("TrackData/Controls/MedusaTracks.csv", header=T, sep=",")
ControlCTData <- read.table("TrackData/Controls/ControlTracks.csv", header=T, sep=",")

## Since our video data did not have any metadata about the time between images, TrackMate (2,3) consider it to
## be 1 minute but the actual time was 90sec, so we need to adjust for that now so the speed is in µm/min.

Control.mc.mean.speed <- as.numeric(ControlMCData$TRACK_MEAN_SPEED)*6/9
Control.ct.mean.speed <- as.numeric(ControlCTData$TRACK_MEAN_SPEED)*6/9

## After that we calculate the normalization:

Control.norm.speed <- Control.mc.mean.speed/mean(Control.ct.mean.speed)

mean(Control.norm.speed) ## 15.42µm/min

##################
## DMSO Control ##
##################

## From here onwards, first we need to create some variables with the ID number of the tracks
## corresponding to the Medusa cells or the controls in each video:

DMSOV1.mc <- as.numeric(c("23","36","58","112","153","154","177","292","306","403","407","455"))
DMSOV2.mc <- as.numeric(c("69","92","118","167","257"))
DMSOV3.mc <- as.numeric(c("14","23","36","45","61","77","79","80","84","87","90","96","115","122","130","133","134","153"))

DMSOV1.ct <- as.numeric(c("9","29","34","46","48","50","59","69","106","178"))
DMSOV2.ct <- as.numeric(c("18","29","49","61","82","91","111","139","148","166"))
DMSOV3.ct <- as.numeric(c("2","3","13","30","32","37","117"))

## Once the ID are prepared, we read the .csv file of each video and extract the data we need. Here 
## we also take into account that for these videos (and all the other onwards) the images were taken
## every 30 seconds instead of 90s, so differently from what we did in control, instead of multiplying
## by 6/9 to adjust for this misscalculation, we multiply by 2:

DMSOData <- read.table("TrackData/DMSO/DMSOV1.csv", header=T, sep=",")
data <- DMSOData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% DMSOV1.mc, ]
DMSOV1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% DMSOV1.ct, ]
DMSOV1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

DMSOData <- read.table("TrackData/DMSO/DMSOV2.csv", header=T, sep=",")
data <- DMSOData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% DMSOV2.mc, ]
DMSOV2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% DMSOV2.ct, ]
DMSOV2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

DMSOData <- read.table("TrackData/DMSO/DMSOV3.csv", header=T, sep=",")
data <- DMSOData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% DMSOV3.mc, ]
DMSOV3.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% DMSOV3.ct, ]
DMSOV3.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

## Finally we combine all the data, and normalize also taking into account the adjustment of speed, 
## with the difference that for all the videos except the controls above, the images were taken
## every 30 seconds:

DMSO.norm.speed <- c(DMSOV1.mc.mean.speed/mean(DMSOV1.ct.mean.speed),
                          DMSOV2.mc.mean.speed/mean(DMSOV2.ct.mean.speed),
                          DMSOV3.mc.mean.speed/mean(DMSOV3.ct.mean.speed))

mean(DMSO.norm.speed) ## 8.96µm/min

###########
## CK666 ##
###########

CKV1.mc <- c(10, 90, 73, 113, 8, 66, 14)
CKV2.1.mc <- c(76, 81, 60, 210, 174, 184)
CKV2.2.mc <- c(132, 91, 324)
CKV3.1.mc <- c(27, 31, 105, 113, 94, 0, 128, 114, 131, 134)
CKV3.2.mc <- c(6, 21, 7, 67, 71, 62, 3, 48, 97)
CKV3.3.mc <- c(19, 61, 83, 20, 17, 37)

CKV1.ct <- c(83, 12, 87, 68, 22, 106, 67)
CKV2.1.ct <- c(1, 53, 40, 4, 69, 21)
CKV2.2.ct <- c(35, 57, 72)
CKV3.1.ct <- c(36, 6, 44, 4, 33, 51, 42, 32, 63, 47, 13)
CKV3.2.ct <- c(17, 27, 28, 31, 34, 46, 2, 44, 38)
CKV3.3.ct <- c(8, 60, 62, 65, 41, 18)

CK666Data <- read.table("TrackData/CK666/CKV1.csv", header=T, sep=",")
data <- CK666Data[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% CKV1.mc, ]
CKV1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% CKV1.ct, ]
CKV1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

CK666Data <- read.table("TrackData/CK666/CKV2.1.csv", header=T, sep=",")
data <- CK666Data[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% CKV2.1.mc, ]
CKV2.1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% CKV2.1.ct, ]
CKV2.1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

CK666Data <- read.table("TrackData/CK666/CKV2.2.csv", header=T, sep=",")
data <- CK666Data[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% CKV2.2.mc, ]
CKV2.2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% CKV2.2.ct, ]
CKV2.2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

CK666Data <- read.table("TrackData/CK666/CKV3.1.csv", header=T, sep=",")
data <- CK666Data[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% CKV3.1.mc, ]
CKV3.1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% CKV3.1.ct, ]
CKV3.1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

CK666Data <- read.table("TrackData/CK666/CKV3.2.csv", header=T, sep=",")
data <- CK666Data[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% CKV3.2.mc, ]
CKV3.2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% CKV3.2.ct, ]
CKV3.2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

CK666Data <- read.table("TrackData/CK666/CKV3.3.csv", header=T, sep=",")
data <- CK666Data[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% CKV3.3.mc, ]
CKV3.3.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)
Filter <- data[data$TRACK_INDEX %in% CKV3.3.ct, ]
CKV3.3.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)

CK666.norm.speed <- c(CKV1.mc.mean.speed/mean(CKV1.ct.mean.speed),
                           CKV2.1.mc.mean.speed/mean(CKV2.1.ct.mean.speed),
                           CKV2.2.mc.mean.speed/mean(CKV2.2.ct.mean.speed),
                           CKV3.1.mc.mean.speed/mean(CKV3.1.ct.mean.speed),
                           CKV3.2.mc.mean.speed/mean(CKV3.2.ct.mean.speed),
                           CKV3.3.mc.mean.speed/mean(CKV3.3.ct.mean.speed))

mean(CK666.norm.speed) ## 2.95µm/min

#################
## Latrunculin ##
#################

LatV1.mc <- as.numeric(c(29, 43, 75, 27, 51, 90, 69, 82, 19, 92))
LatV2.mc <- as.numeric(c("21","33","93","131","165","387"))
LatV3.1.mc <- as.numeric(c("50","88","91","93"))
LatV3.2.mc <- as.numeric(c("8","25","61","72","76","84","101"))

LatV1.ct <- as.numeric(c("1","2","4","5","11","12","14","17","60"))
LatV2.ct <- as.numeric(c("23","35","47","67","69","84","106","238","378"))
LatV3.1.ct <- as.numeric(c("1","3","6","11","16","22","26"))
LatV3.2.ct <- as.numeric(c("0","2","3","6","8","11","14","16","27","30"))

LatData <- read.table("TrackData/Latrunculin/LatV1.csv", header=T, sep=",")
data <- LatData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% LatV1.mc, ]
LatV1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% LatV1.ct, ]
LatV1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

LatData <- read.table("TrackData/Latrunculin/LatV2.csv", header=T, sep=",")
data <- LatData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% LatV2.mc, ]
LatV2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% LatV2.ct, ]
LatV2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

LatData <- read.table("TrackData/Latrunculin/LatV3.1.csv", header=T, sep=",")
data <- LatData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% LatV3.1.mc, ]
LatV3.1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% LatV3.1.ct, ]
LatV3.1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

LatData <- read.table("TrackData/Latrunculin/LatV3.2.csv", header=T, sep=",")
data <- LatData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% LatV3.2.mc, ]
LatV3.2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% LatV3.2.ct, ]
LatV3.2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

Lat.norm.speed <- c(LatV1.mc.mean.speed/mean(LatV1.ct.mean.speed),
                         LatV2.mc.mean.speed/mean(LatV2.ct.mean.speed),
                         LatV3.1.mc.mean.speed/mean(LatV3.1.ct.mean.speed),
                         LatV3.2.mc.mean.speed/mean(LatV3.2.ct.mean.speed))

mean(Lat.norm.speed) ## 6.85µm/min

##################
## Blebbistatin ##
##################

BlbV1.mc <- as.numeric(c("99","106","149","155","172","202","241","253","260","284","525"))
BlbV2.1.mc <- as.numeric(c("18","43","69","75","131"))
BlbV2.2.mc <- as.numeric(c("32","51","69","104"))
BlbV3.1.mc <- as.numeric(c("2","3","11","18","28","66"))
BlbV3.2.mc <- as.numeric(c("1","11","18"))
BlbV3.3.mc <- as.numeric(c("23","67","74","90"))

BlbV1.ct <- as.numeric(c("71","77","92","98","117","163","207","212","311","383"))
BlbV2.1.ct <- as.numeric(c("9","40","45","51","74"))
BlbV2.2.ct <- as.numeric(c("18","71","88","113","124"))
BlbV3.1.ct <- as.numeric(c("1","16","31","74","75","79"))
BlbV3.2.ct <- as.numeric(c("0","8","17"))
BlbV3.3.ct <- as.numeric(c("1","3","14","25"))

BlbData <- read.table("TrackData/Blebbistatin/BlbV1.csv", header=T, sep=",")
data <- BlbData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% BlbV1.mc, ]
BlbV1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% BlbV1.ct, ]
BlbV1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

BlbData <- read.table("TrackData/Blebbistatin/BlbV2.1.csv", header=T, sep=",")
data <- BlbData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% BlbV2.1.mc, ]
BlbV2.1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% BlbV2.1.ct, ]
BlbV2.1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

BlbData <- read.table("TrackData/Blebbistatin/BlbV2.2.csv", header=T, sep=",")
data <- BlbData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% BlbV2.2.mc, ]
BlbV2.2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% BlbV2.2.ct, ]
BlbV2.2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

BlbData <- read.table("TrackData/Blebbistatin/BlbV3.1.csv", header=T, sep=",")
data <- BlbData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% BlbV3.1.mc, ]
BlbV3.1.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% BlbV3.1.ct, ]
BlbV3.1.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

BlbData <- read.table("TrackData/Blebbistatin/BlbV3.2.csv", header=T, sep=",")
data <- BlbData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% BlbV3.2.mc, ]
BlbV3.2.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2
Filter <- data[data$TRACK_INDEX %in% BlbV3.2.ct, ]
BlbV3.2.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)*2

BlbData <- read.table("TrackData/Blebbistatin/BlbV3.3.csv", header=T, sep=",")
data <- BlbData[-c(1,2,3),]
Filter <- data[data$TRACK_INDEX %in% BlbV3.3.mc, ]
BlbV3.3.mc.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)
Filter <- data[data$TRACK_INDEX %in% BlbV3.3.ct, ]
BlbV3.3.ct.mean.speed <- as.numeric(Filter$TRACK_MEAN_SPEED)

Blebb.norm.speed <- c(BlbV1.mc.mean.speed/mean(BlbV1.ct.mean.speed),
                           BlbV2.1.mc.mean.speed/mean(BlbV2.1.ct.mean.speed),
                           BlbV2.2.mc.mean.speed/mean(BlbV2.2.ct.mean.speed),
                           BlbV3.1.mc.mean.speed/mean(BlbV3.1.ct.mean.speed),
                           BlbV3.2.mc.mean.speed/mean(BlbV3.2.ct.mean.speed),
                           BlbV3.3.mc.mean.speed/mean(BlbV3.3.ct.mean.speed))

mean(Blebb.norm.speed) ## 2.49µm/min

###########################################################################################################
## 2. Statistical analysis and plotting                                                                  ##
###########################################################################################################

## After having extracted the information needed, we combine all of it into a dataframe:

ControlSample <- c(rep("Control",9))
DMSOSample <- c(rep("DMSO",35))
CKSample <- c(rep("CK666",41))
LatSample <- c(rep("Latrunculin",27))
BlbSample <- c(rep("Blebbistatin",33))

Sample <- c(CKSample,BlbSample,LatSample,DMSOSample,ControlSample)
Norm_Speed <- c(CK666.norm.speed,Blebb.norm.speed,Lat.norm.speed,DMSO.norm.speed,Control.norm.speed)

InhibitorsData <- data.frame(Sample,Norm_Speed)

InhibitorsData$Sample <- factor(InhibitorsData$Sample, levels = c("Control","DMSO","Latrunculin","CK666","Blebbistatin"))

## After this, we proceed with the statistical analysis, checking first the normality of the data before deciding which
## statistical test will be used:

shapiro.test(Control.norm.speed) # p-value = 0.11
shapiro.test(DMSO.norm.speed) # p-value = 0.028
shapiro.test(CK666.norm.speed) # p-value = 0.028
shapiro.test(Lat.norm.speed) # p-value = 0.00018
shapiro.test(Blebb.norm.speed) # p-value = 0.00016

## As we can see, any of them except the control follow a normal distribution, so the appropiate statistical test is the 
## wilcoxon test:

wilcox.test(Control.norm.speed, DMSO.norm.speed, alternative = "greater") # p-value: 0.0003
wilcox.test(DMSO.norm.speed, Lat.norm.speed, alternative = "greater") # p-value: 0.03
wilcox.test(DMSO.norm.speed, CK666.norm.speed, alternative = "greater") # p-value: 1.75e-10
wilcox.test(DMSO.norm.speed, Blebb.norm.speed, alternative = "greater") # p-value: 7.443e-11

## We proceed with generating a violin plot:

ggplot(InhibitorsData, aes(x=Sample, y=Norm_Speed, fill=Sample)) +
  geom_violin() + 
  labs(title = "Normalized speed of medusa cells after different treatments", x="Treatment", y="Speed Normalized") +
  theme_light()  +
  theme(axis.title = element_blank()) +
  scale_fill_manual(values=c("#E6AF2E66","#9A031E99","#F4845F99","#F3A68D99","#F3665F99")) +
  theme(axis.title = element_text(face = "bold.italic", size = 11)) +
  theme(plot.title = element_text(face = "bold.italic", size = 13)) +
  theme(axis.text = element_text(face = "bold")) +
  geom_signif(data=InhibitorsData,comparisons=list(c("Control","DMSO")),map_signif_level = TRUE,annotations="***", y_position = 30) +
  geom_signif(data=InhibitorsData,comparisons=list(c("DMSO","Latrunculin")),map_signif_level = TRUE,annotations="*", y_position = 25) +
  geom_signif(data=InhibitorsData,comparisons=list(c("DMSO","CK666")),map_signif_level = TRUE,annotations="****", y_position = 27.5) +
  geom_signif(data=InhibitorsData,comparisons=list(c("DMSO","Blebbistatin")),map_signif_level = TRUE,annotations="****", y_position = 30) +
  theme(legend.position = "none")

###########################################################################################################

## Citations:
## 1. Schindelin, J., Arganda-Carreras, I., Frise, E. et al. Fiji: an open-source platform for 
##    biological-image analysis. Nat Methods 9, 676-682 (2012). https://doi.org/10.1038/nmeth.2019
## 2. Tinevez JY, Perry N, Schindelin J, Hoopes GM, Reynolds GD, Laplantine E, Bednarek SY, Shorte SL,
##    Eliceiri KW. TrackMate: An open and extensible platform for single-particle tracking. Methods. 2017 Feb
##    15;115:80-90. doi: 10.1016/j.ymeth.2016.09.016. Epub 2016 Oct 3. PMID: 27713081.
## 3. Ershov, D., Phan, MS., Pylvänäinen, J.W. et al. TrackMate 7: integrating state-of-the-art segmentation
##    algorithms into tracking pipelines. Nat Methods 19, 829–832 (2022). https://doi.org/10.1038/s41592-022-01507-1
## 4. H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.
## 5. Ahlmann-Eltze, C., & Patil, I. (2021). ggsignif: R Package for Displaying Significance Brackets for 'ggplot2'. 
##    PsyArxiv. doi:10.31234/osf.io/7awm6

